language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - "pip install -r tests/requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
  - "python setup.py develop"
script: 
    python setup.py test
after_success:
    coveralls --rcfile=.coveragerc
